<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <!--<OutputType>Exe</OutputType>-->
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <DebugType>portable</DebugType>
    <DebugSymbols>true</DebugSymbols>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ApplicationIcon>./wwwroot/favicon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AigcDetectorSharp.Core\AigcDetectorSharp.Core.csproj" />
      <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.2739.15" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\**" LinkBase="wwwroot">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </None>
    <None Include="..\model_zhv3\AIGC_detector_zhv3.onnx" Link="model_zhv3\AIGC_detector_zhv3.onnx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </None>
    <None Include="..\model_zhv3\tokenizer_export\**" LinkBase="model_zhv3\tokenizer_export">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </None>
    <None Include="..\model_env3\AIGC_detector_env3.onnx" Link="model_env3\AIGC_detector_env3.onnx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </None>
    <None Include="..\model_env3\tokenizer_export\**" LinkBase="model_env3\tokenizer_export">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Content Remove="wwwroot\favicon.ico" />
  </ItemGroup>
</Project>
