<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DocumentFormat.OpenXml" Version="3.5.1" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.24.4" />
    <PackageReference Include="PdfPig" Version="0.1.14" />
    <PackageReference Include="Tokenizers.DotNet" Version="1.4.0" />
    <PackageReference Include="Tokenizers.DotNet.runtime.linux-x64" Version="1.4.0" />
    <PackageReference Include="Tokenizers.DotNet.runtime.win-x64" Version="1.4.0" />
  </ItemGroup>

</Project>
